- name: Maquina con nginx
  hosts: nginxserver
  become: true
  vars: 
    servername: pablolinari
    configpath: /etc/nginx/conf.d/
    indexpath: /var/www/{{servername}}/html/
    puerto: 80
    htmlcontent: <html><h1>Bienvenidos a la web de Pablo Linari Perez en Practicas ISE (nginx)</h1></html>

  tasks:
    - name: instalar nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest ## lo instal y si no es la version mas nueva lo actualiza.
    - name: Habilitar nginx
      ansible.builtin.service: 
        name: nginx
        state: started
        enabled: yes
    - name: Aniadir nginx al firewall y habilitarlo 
      ansible.posix.firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true
        offline: true
    - name: Creo la carpeta de mi servidor de nginx
      ansible.builtin.file:
        path: "{{indexpath}}"
        owner: nginx
        group: nginx
        mode: '0755'
        state: directory

    - name: Pongo el contenido html en el archivo
      ansible.builtin.copy:
        content: "{{htmlcontent}}"
        dest: "{{ indexpath }}/index.html"
 
    - name: Creo la carpeta configuracion
      ansible.builtin.file:
        path: "{{configpath}}"
        state: directory
    - name: Creo el archivo html
      ansible.builtin.file:
        path: "{{configpath}}/{{servername}}.conf"
        owner: nginx
        group: nginx
        mode: '0755'
        state: touch
    - name: Pongo la configuracion del servidor
      ansible.builtin.copy:
        content: |
          server {
            listen {{puerto}};
            listen [::]:{{puerto}};

            root {{indexpath}};
            index index.html index.htm index.nginx-debian.html;

            server_name {{servername}} www.{{servername}};

            location / {
                  try_files $uri $uri/ =404;
            }
          }
        dest: "{{configpath}}/{{servername}}.conf"
    
    - name: Reiniciar nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded

- name: Maquina con apache
  hosts: apacheserver
  become: true
  vars: 
    configpath: /etc/httpd/conf/httpd.conf
    defaultpath: /etc/httpd/conf.d/welcome.conf
    indexpath: /var/www/html
    servername: pablolinari
    puerto: 80
    htmlcontent: <html><h1>Bienvenidos a la web de Pablo Linari Perez en Practicas ISE (apache)</h1></html>
    

  tasks: 
    - name: instalar httpd
      ansible.builtin.dnf: 
        name: httpd
        state: latest
    - name: elimino configuracion por defecto
      ansible.builtin.file:
        path: "{{defaultpath}}"
        state: absent
    - name: editar nombre del servidor
      ansible.builtin.lineinfile: 
        path: "{{configpath}}"
        regexp: '^#ServerName'
        line: "ServerName www.{{servername}}.com:{{puerto}}"
        state: present
    - name: Cambiar linea 147 
      ansible.builtin.lineinfile: 
        path: "{{configpath}}"
        regexp: 'Options Indexes FollowSymLinks'
        line: "Options FollowSymLinks"
        state: present
    - name: Cambiar linea 154 override all 
      ansible.builtin.lineinfile: 
        path: "{{configpath}}"
        regexp: 'AllowOverride None'
        line: "AllowOverride All"
        state: present
    - name: Cambiar linea 167 
      ansible.builtin.lineinfile: 
        path: "{{configpath}}"
        regexp: 'DirectoryIndex index.html'
        line: "DirectoryIndex index.html index.php index.cgi"
        state: present
    - name: Aniado server tokens al final 
      ansible.builtin.lineinfile: 
        path: "{{configpath}}"
        line: "ServerTokens Prod"
        state: present
    - name: Habilitar http
      ansible.builtin.service: 
        name: httpd
        state: started
        enabled: yes
    - name: Aniadir httpd al firewall y habilitarlo 
      ansible.posix.firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true
        offline: true
    
    - name: Pongo el contenido html en el archivo
      ansible.builtin.copy:
        content: "{{htmlcontent}}"
        dest: "{{indexpath}}/index.html"
        owner: apache
        group: apache
        mode: '0644'

    - name: Reiniciar httpd
      ansible.builtin.service:
        name: httpd
        state: reloaded
