--- 
- name: variables
  hosts: mvise
  become: true
  vars:
    username: admin
    groupname: wheel
 
- name: Crear usuario 
  user: 
    name: "{{username}}"
    state: present
    create_home: true

- name: Ejecutar comandos sin contrasenia
  lineinfile:
    path: /etc/sudoers
    line: "{{username}} ALL=(ALL) NOPASSWD: ALL "
    state: present

- name: copiar llave publica al usuario 
  ansible.posix.authorized_key:
    user: "{{username}}"
    key: "{{lookup('file','~/.ssh/id_rsa.pub')}}"
    state: present
- name: descomentar archivo sshdconfig 
  lineinfile:
  path: /etc/ssh/sshd_config
  line: "PubkeyAuthentication yes"
  state: present
- name: descomentar archivo sshdconfig otra linea
  lineinfile:
  path: /etc/ssh/sshd_config
  line: "AuthorizedKeysFile .ssh/authorized_keys"
  state: present
- name: 
  group:
    name: "{{groupname}}"
    state: present
- name: Reiniciar sshd
  service: 
    name: sshd
    state: restarted




