- name: Maquina con nginx
  hosts: nginxserver
  become: true
  vars: 
    servername: pablolinari
    configpath: /etc/nginx/conf.d/
    indexpath: /var/www/{{servername}}/html/
    port: 80
    htmlcontent: <html><h1>Bienvenidos a la web de Pablo Linari Perez en Prácticas ISE</h1></html>

  tasks:
    - name: instalar nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest ## lo instal y si no es la version mas nueva lo actualiza.
    - name: Habilitar nginx
      ansible.builtin.service: 
        name: nginx
        state: started
        enabled: yes
    - name: Aniadir nginx al firewall y habilitarlo 
      ansible.posix.firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true
        offline: true
    - name: Creo la carpeta de mi servidor de nginx
      ansible.builtin.file:
        path: "{{indexpath}}"
        state: directory

    - name: Pongo el contenido html en el archivo
      ansible.builtin.copy:
        content: "{{htmlcontent}}"
        dest: "{{ indexpath }}/index.html"
 
    - name: Creo la carpeta configuracion
      ansible.builtin.file:
        path: "{{configpath}}"
        state: directory
    - name: Creo el archivo html
      ansible.builtin.file:
        path: "{{configpath}}/{{servername}}.conf"
        state: touch
    - name: Pongo la configuracion del servidor
      ansible.builtin.copy:
        content: |
          server {
            listen {{port}};
            listen [::]:{{port}};

            root {{indexpath}};
            index index.html index.htm index.nginx-debian.html;

            server_name {{servername}} www.{{servername}};

            location / {
                  try_files $uri $uri/ =404;
            }
          }
        dest: "{{configpath}}/{{servername}}.conf"
    
    - name: Reiniciar nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

- name: Maquina con HTTPD
  hosts: httpdserver
  become: true
  vars: 
    configpath: /etc/httpd/conf/httpd.conf
    indexpath: /var/www/html
    servername: pablolinari
    port: 80
    htmlcontent: <html><h1>Bienvenidos a la web de Pablo Linari Perez en Prácticas ISE</h1></html>
    

  tasks: 
    - name: instalar httpd
      ansible.builtin.dnf: 
        name: httpd
        state: latest
    - name: editar nombre del servidor
      ansible.builtin.lineinfile: 
        path: "{{configpath}}"
        regexp: '^#ServerName'
        line: "ServerName www.{{servername}}.com:{{port}}"
        state: present
    - name: Habilitar http
      ansible.builtin.service: 
        name: httpd
        state: started
        enabled: yes
    - name: Aniadir httpd al firewall y habilitarlo 
      ansible.posix.firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true
        offline: true
    
    - name: Pongo el contenido html en el archivo
      ansible.builtin.copy:
        content: "{{htmlcontent}}"
        dest: "{{indexpath}}/index.html"
